version: '3.7'


services:


  movie_app:
    container_name: movie_admin
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db

#  elasticsearch:
#    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
#    environment:
#      - discovery.type=single-node
#    ports:
#      - 9200:9200
#      - 9300:9300
#    depends_on:
#      - db

  db:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    ports:
      - 5432:5432
    volumes:
    - /home/klimov/PycharmProjects/yandex.praktikum/pg_data:/var/lib/postgresql/data
